export const products = [
    {
      id: 1001,
      name: "Take Out Bag",
      category: "Paper Bags",
      price: 230,
      description: "The Bag is sturdy, strong, and used as a carrier, food/product can comfortably be taken out or delivered.",
      imageUrl: "/1001.webp",
      rating: 4.7,
      stock: 10000,
      colour: "Kraft Brown",
    },
    {
      id: 1002,
      name: "Twisted Handle Gift Bag",
      category: "Paper Bags",
      price: 400,
      description: "The Bag is sturdy, strong, made from Kraft paper 100gsm with twisted rope handle.",
      imageUrl: "/1002.webp",
      rating: 4.9,
      stock: 25000,
      colour: "Kraft Brown",
    },
    {
      id: 1003,
      name: "Burger Bag",
      category: "Paper Bags",
      price: 100,
      description: "The bag is leak resistant and can comfortably be eaten directly from the bag.",
      imageUrl: "/1003.webp",
      rating: 4.8,
      stock: 15000,
      colour: "Kraft Brown",
    },
    
    {
        id: 1004,
        name: "Pastry Bag",
        category: "Paper Bags",
        price: 180,
        description: "The Bag is sturdy, strong, made from Kraft paper 100gsm and used as a carrier, food/product can comfortably be taken out or delivered.",
        imageUrl: "/1004.webp",
        rating: 4.9,
        stock: 8000,
        colour: "Kraft Brown"
      },
      {
        id: 2001,
        name: "Black & White (Checkered) Grease Proof Paper",
        category: "Grease Proof Papers",
        price: 100,
        description: "Food Wrapping paper made from greaseproof paper.",
        imageUrl: "/2001.webp",
        rating: 4.8,
        stock: 9000,
        colour: "Black and White"
      },
      {
        id: 2002,
        name: "Generic Grease Proof Paper",
        category: "Grease Proof Papers",
        price: 100,
        description: "Food Wrapping paper suitable for contact grill / grill presses, take away deli panini, baguettes and snacks.",
        imageUrl: "/2002.webp",
        rating: 4.4,
        stock: 11000,
        colour: "Green"
      },
      {
        id: 2003,
        name: "Red & White (Checkered) Grease Proof Paper",
        category: "Grease Proof Papers",
        price: 100,
        description: "The paper is a disposable non-stick paper suitable for contact grill / grill presses, take away deli panini, baguettes and snacks",
        imageUrl: "/2003.webp",
        rating: 4.7,
        stock: 5000,
        colour: "Red and  White"
      },
      {
        id: 2004,
        name: "White Grease Proof Paper",
        category: "Grease Proof Papers",
        price: 220,
        description: "Food Wrapping paper made from greaseproof paper.",
        imageUrl: "/2003.webp",
        rating: 4.5,
        stock: 6000,
        colour: "White"
      },
      {
        id: 3001,
        name: "Large White Lunch Pack",
        category: "Lunch Packs",
        price: 230,
        description: "The pack can be easily torn (tear off), sturdy, strong, leak resistant and used as a bowl, food can comfortably be eaten directly from the box.",
        imageUrl: "/3001.webp",
        rating: 4.4,
        stock: 4500,
        colour: "White"
      },
      {
        id: 3002,
        name: "Small Black Lunch Pack",
        category: "Lunch Packs",
        price: 165,
        description: "The pack is made from FBB paper 300gsm, with PE lining and can be easily torn (tear off).",
        imageUrl: "/3002.webp",
        rating: 4.9,
        stock: 3000,
        colour: "Black"
      },
      {
        id: 3003,
        name: "Medium Black Lunch Pack",
        category: "Lunch Packs",
        price: 230,
        description: "The pack is made from FBB paper 300gsm, with PE lining and can hold any type of foods, whether it is hot, cold, wet or dry.",
        imageUrl: "/3003.webp",
        rating: 4.8,
        stock: 5000,
        colour: "Black"
      },
      {
        id: 3004,
        name: "Medium Kraft (Brown) Lunch Pack",
        category: "Lunch Packs",
        price: 275,
        description: "The pack can be easily torn (tear off), sturdy, strong, leak resistant and used as a bowl, food can comfortably be eaten directly from the box.",
        imageUrl: "/3004.webp",
        rating: 4.7,
        stock: 6000,
        colour: "Kraft Brown"
      },
      {
        id: 4001,
        name: "Boat Tray",
        category: "Snack Trays & Packs",
        price: 120,
        description: "Boat Tray can hold any type of foods/product, whether it is hot, cold, wet or dry.",
        imageUrl: "/4001.webp",
        rating: 4.4,
        stock: 3500,
        colour: "White"
      },
      {
        id: 4002,
        name: "Small Chops Pack",
        category: "Snack Trays & Packs",
        price: 135,
        description: "The pack is Suitable for Small Chops, fish and chicken wings with French fries, and can comfortably be eaten directly from the box.",
        imageUrl: "/4002.webp",
        rating: 4.6,
        stock: 8000,
        colour: "White"
      },
      {
        id: 4003,
        name: "Pop Corn Pack",
        category: "Snack Trays & Packs",
        price: 135,
        description: "The pack is suitable for pop corn and other finger foods.",
        imageUrl: "/4003.webp",
        rating: 4.5,
        stock: 7500,
        colour: "White"
      },
      {
        id: 4004,
        name: "Chips Pack",
        category: "Snack Trays & Packs",
        price: 85,
        description: "The pack is suitable for French fries and finger foods.",
        imageUrl: "/4004.webp",
        rating: 4.8,
        stock: 2500,
        colour: "White"
      },
      {
        id: 5001,
        name: "8″ Pizza Pack",
        category: "Pizza Boxes",
        price: 400,
        description: "This packaging is aimed at take-away outlets, petrol stations, cafeterias, markets.  It is also ideal for catering and the event industry.",
        imageUrl: "/5001.webp",
        rating: 4.3,
        stock: 1000,
        colour: "Kraft Brown"
      },
      {
        id: 5002,
        name: "10″ Pizza Pack",
        category: "Pizza Boxes",
        price: 400,
        description: "This packaging is ideal for catering and the event industry.",
        imageUrl: "/5002.webp",
        rating: 4.3,
        stock: 1500,
        colour: "Kraft Brown"
      },
      {
        id: 5003,
        name: "12″ Pizza Pack",
        category: "Pizza Boxes",
        price: 500,
        description: "This packaging is made from e-flute carton 3 ply and ideal for catering and the event industry.",
        imageUrl: "/5003.webp",
        rating: 4.3,
        stock: 3500,
        colour: "Kraft Brown"
      },
      {
        id: 5004,
        name: "14″ Pizza Pack",
        category: "Pizza Boxes",
        price: 550,
        description: "The box made from e-flute carton 3 ply can be easily torn (tear off), sturdy, strong, food can comfortably be eaten directly from the box.",
        imageUrl: "/5004.webp",
        rating: 4.3,
        stock: 1200,
        colour: "Kraft Brown"
      }
  ];
  